# Python Assignment
Topic: 3D Arrays and Dictionaries


# Part A – 3D Arrays  

# Question 1  
## Create the following 3D array.

Layer 1

[1, 2, 3]
[4, 5, 6]

Layer 2

[7, 8, 9]
[10, 11, 12]

In [ ]:
Write a Python program to:

Print the complete 3D array.
Print the first layer.
Print the second row of the second layer.
Print the element 11.

In [12]:
import numpy as np

array_3d = np.array([
   [[1,2,3],
    [4,5,6]],

   [[7,8,9],
    [10,11,12]]
])
print("Print the complete 3D array.")
print(array_3d)
print("Print the first layer.")
print(array_3d[0])
print("Print the second row of the second layer.")
print(array_3d[1,1])
print("Print the element 11.")
print(array_3d[1,1,1])

Print the complete 3D array.
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Print the first layer.
[[1 2 3]
 [4 5 6]]
Print the second row of the second layer.
[10 11 12]
Print the element 11.
11


# Question 2  

Using the same 3D array, reverse the order of layers.

Expected Output

Layer 2

[7, 8, 9]
[10,11,12]

Layer 1

[1,2,3]
[4,5,6]

In [29]:
import numpy as np

array_3d = np.array ([
    [[1,2,3],
     [4,5,6]],

    [[7,8,9],
     [10,11,12]]
])

print("reverse the order of layers")
reverse_layer_order = array_3d[::-1, :, :]
print(reverse_layer_order)
#reverse_layer_order = np.flip(array_3d, axis=0)
#print(reverse_layer_order)


reverse the order of layers
[[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


# Question 3  

##  Reverse every row inside every layer.

Expected Output

In [28]:
import numpy as np

array_3d = np.array([
    [[1,2,3],
     [4,5,6]],

    [[7,8,9],
     [10,11,12]]
])

print("Reverse every row inside every layer")
reverse_every_row = array_3d[:, ::-1, :]
#reverse_every_row = np.flip(array_3d, axis=1)
print(reverse_every_row)


Reverse every row inside every layer
[[[ 4  5  6]
  [ 1  2  3]]

 [[10 11 12]
  [ 7  8  9]]]


# Question 4  

Completely reverse the entire 3D array by reversing:

    the order of layers,
    the order of rows inside each layer,
    the elements inside every row.

Expected Output

[12,11,10]
[9,8,7]
[6,5,4]
[3,2,1]

In [27]:
import numpy as np

array_3d = np.array([
    [[1,2,3],
     [4,5,6]],

    [[7,8,9],
     [10,11,12]]
])

flip_entire_array = array_3d[::-1, ::-1, ::-1]
print(flip_entire_array)
#fully_reversed_3d = np.flip(array_3d)
#print(fully_reversed_3d)
flattened_array = array_3d.flatten()
print(flattened_array)

[[[12 11 10]
  [ 9  8  7]]

 [[ 6  5  4]
  [ 3  2  1]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Part B – Dictionaries

In [ ]:
# Create a dictionary to store the following student details.

| Key        | Value   |
| ---------- | ------- |
| Roll No    | 101     |
| Name       | Alice   |
| Age        | 20      |
| Department | AI & DS |
| CGPA       | 8.9     |

Display all the information. (use print)

In [31]:

student_details = {
    "Roll No": 101,
    "Name": "Alice",
    "Age": 20,
    "Department": "AI & DS",
    "CGPA": 8.9
}
print(student_details)

{'Roll No': 101, 'Name': 'Alice', 'Age': 20, 'Department': 'AI & DS', 'CGPA': 8.9}


In [ ]:
# Question 6  

Using the dictionary created above,

    Update the CGPA to 9.2
    Add a new key named City with value Chennai
    Display the updated dictionary.

In [32]:
student_details = {
    "Roll No": 101,
    "Name": "Alice",
    "Age": 20,
    "Department": "AI & DS",
    "CGPA": 8.9
}

student_details["CGPA"] = 9.2
student_details["City"] = "Chennai"
print(student_details)

{'Roll No': 101, 'Name': 'Alice', 'Age': 20, 'Department': 'AI & DS', 'CGPA': 9.2, 'City': 'Chennai'}


In [ ]:
# Question 7  

Write a program to print

    all keys
    all values
    all key-value pairs

using appropriate dictionary methods.

In [34]:
student_details = {
    "Roll No": 101,
    "Name": "Alice",
    "Age": 20,
    "Department": "AI & DS",
    "CGPA": 9.2,
    "City": "Chennai"
}

print(list(student_details.keys()))
print(list(student_details.values()))
for key, value in student_details.items():
    print(f"{key}: {value}")

['Roll No', 'Name', 'Age', 'Department', 'CGPA', 'City']
[101, 'Alice', 20, 'AI & DS', 9.2, 'Chennai']
Roll No: 101
Name: Alice
Age: 20
Department: AI & DS
CGPA: 9.2
City: Chennai


In [ ]:
# Question 8  

Create the following nested dictionary.

students = {
    "Student1": {
        "Name": "John",
        "Age": 22
    },
    "Student2": {
        "Name": "Alice",
        "Age": 21
    },
    "Student3": {
        "Name": "David",
        "Age": 20
    }
}

Write a program to

    Print the name of Student2.
    Print the age of Student3.
    Display all student names using a loop.

In [41]:
students = {
    "Student1": {
        "Name": "John",
        "Age": 22
    },
    "Student2": {
        "Name": "Alice",
        "Age": 21
    },
    "Student3": {
        "Name": "David",
        "Age": 20
    }
}

print(students["Student2"]["Name"])
print(students["Student3"]["Age"])
for id, details in students.items():
    print(details["Name"])

Alice
20
John
Alice
David


In [ ]:
# Question 9  

Create a dictionary of five products.

Example

    Laptop
    Mouse
    Keyboard
    Monitor
    Printer

Each product should contain

    Product Name
    Price
    Quantity

Write a program to

    Display all products.
    Print the product with the highest price.
    Calculate the total inventory value

(Formula:  Inventory Value = Price × Quantity)

In [48]:
products = {
    "P1": {"Product Name": "Laptop", "Price": 75000.00, "Quantity": 100},
    "P2": {"Product Name": "Mouse", "Price": 200.00, "Quantity": 50},
    "P3": {"Product Name": "Keyboard", "Price": 2500.00, "Quantity": 35},
    "P4": {"Product Name": "Monitor", "Price": 15000.00, "Quantity": 25},
    "P5": {"Product Name": "Printer", "Price": 25000.00, "Quantity": 15}
}

for id, details in products.items():
    print(f"Product Name: {details['Product Name']} - Price : {details['Price']} - Quantity : {details['Quantity']}")

highest_priced_product = None
highest_price = 0.0
for id, details in products.items():
    if details["Price"] > highest_price:
        highest_price = details["Price"]
        highest_priced_product = details["Product Name"]
print(f"Highest Priced Product : {highest_priced_product}, Price : {highest_price}")

total_inventory_value = 0.0
for id, details in products.items():
    product_value = details["Price"] * details["Quantity"]
    total_inventory_value += product_value
print(f"Total Inventory value : {total_inventory_value}")


Product Name: Laptop - Price : 75000.0 - Quantity : 100
Product Name: Mouse - Price : 200.0 - Quantity : 50
Product Name: Keyboard - Price : 2500.0 - Quantity : 35
Product Name: Monitor - Price : 15000.0 - Quantity : 25
Product Name: Printer - Price : 25000.0 - Quantity : 15
Highest Priced Product : Laptop, Price : 75000.0
Total Inventory value : 8347500.0


In [ ]:
# Question 10

Create a dictionary of five students and their marks.

Example

    Alice : 85
    Bob : 92
    Charlie : 78
    David : 88
    Emma : 95

Write a Python program to

    Find the student with the highest marks.
    Find the student with the lowest marks.
    Calculate the average marks.
    Display students who scored more than 85.

In [53]:
student_marks = {
    "Alice": 85,
    "Bob": 92,
    "Charlie": 78,
    "David": 88,
    "Emma": 95
}

highest_mark_student = max(student_marks, key=student_marks.get)
lowest_mark_student = min(student_marks, key=student_marks.get)
print(f"Student with highest marks : {highest_mark_student}")
print(f"Student with lowest marks : {lowest_mark_student}")

total_marks = sum(student_marks.values())
num_students = len(student_marks)
average_marks = total_marks/num_students
print(f"Average marks : {average_marks}")
print(f"Students scored more than 85")
for student, marks in student_marks.items():
    if marks > 85:
        print(f"Name : {student}, Marks: {marks}")


Student with highest marks : Emma
Student with lowest marks : Charlie
Average marks : 87.6
Students scored more than 85
Name : Bob, Marks: 92
Name : David, Marks: 88
Name : Emma, Marks: 95
